"""Export formatters for generated Fc sequences (GenBank flat file, CSV report).

All functions are pure string builders with defensive validation so they can be
called from the UI layer without leaking exceptions or producing oversized output.
"""

import csv
import io
import re
from datetime import date
from typing import List

from fc_engineer.core import get_eu_position

MAX_EXPORT_SEQUENCE_LENGTH = 10000
MAX_METADATA_LENGTH = 200

_MONTHS = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN",
           "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"]


def sanitize_locus(locus: str) -> str:
    """Reduce a locus name to GenBank-safe characters ([A-Za-z0-9_.-]), max 16 chars."""
    if not isinstance(locus, str):
        return "UNKNOWN"
    safe = re.sub(r"[^A-Za-z0-9_.-]", "_", locus)
    return safe[:16] if safe else "UNKNOWN"


def _genbank_date() -> str:
    today = date.today()
    return f"{today.day:02d}-{_MONTHS[today.month - 1]}-{today.year}"


def format_genbank(locus: str, sequence: str, definition: str = "") -> str:
    """Build a minimal GenBank-style protein record. Returns '' on invalid input."""
    if not isinstance(sequence, str) or not sequence:
        return ""
    if len(sequence) > MAX_EXPORT_SEQUENCE_LENGTH:
        return ""
    if not re.fullmatch(r"[A-Z]+", sequence):
        return ""
    definition = (definition or "")[:MAX_METADATA_LENGTH]
    safe_locus = sanitize_locus(locus)

    lines: List[str] = []
    lines.append(f"LOCUS       {safe_locus:<16}{len(sequence):>9} aa    linear   UNK {_genbank_date()}")
    lines.append(f"DEFINITION  {definition}.")
    lines.append(f"ACCESSION   {safe_locus}")
    lines.append("KEYWORDS    .")
    lines.append("SOURCE      .")
    lines.append("  ORGANISM  .")
    lines.append("COMMENT     Generated by Fc Engineering Studio.")
    lines.append("FEATURES             Location/Qualifiers")
    lines.append(f"     source          1..{len(sequence)}")
    lines.append('                     /organism=["Homo sapiens"]')
    lines.append("ORIGIN")

    # 60 residues per line in 10-residue blocks, position right-justified (width 9)
    for start in range(0, len(sequence), 60):
        chunk = sequence[start:start + 60]
        blocks = " ".join(chunk[i:i + 10] for i in range(0, len(chunk), 10))
        lines.append(f"{start + 1:>9} {blocks}")
    lines.append("//")
    return "\n".join(lines) + "\n"


def format_csv_report(isotype: str, allotype: str, mutations: str,
                      wt_seq: str, mut_seq: str) -> str:
    """Build a per-position CSV report comparing WT and mutant sequences.

    Columns: eu_position, wt_aa, mut_aa, mutated. EU position is left empty for
    indices that do not map to an EU number (e.g., hinge gaps).
    Returns '' on invalid input.
    """
    if not isinstance(wt_seq, str) or not wt_seq or not isinstance(mut_seq, str):
        return ""
    if max(len(wt_seq), len(mut_seq)) > MAX_EXPORT_SEQUENCE_LENGTH:
        return ""

    buf = io.StringIO()
    writer = csv.writer(buf, lineterminator="\n")
    writer.writerow(["# isotype", isotype or "", allotype or "", mutations or ""])
    writer.writerow(["eu_position", "wt_aa", "mut_aa", "mutated"])
    for idx in range(max(len(wt_seq), len(mut_seq))):
        wt = wt_seq[idx] if idx < len(wt_seq) else ""
        mut = mut_seq[idx] if idx < len(mut_seq) else ""
        pos = get_eu_position(idx, isotype or "")
        writer.writerow([pos if pos is not None else "", wt, mut,
                         "yes" if wt != mut else "no"])
    return buf.getvalue()
